#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := i2s_adc_dac_with_interruption_and_bugs

include $(IDF_PATH)/make/project.mk
